name: WindowsRDP

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 99999999

    steps:
    - name: Preparing Ngrok
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/Metehanse/WindowsRDP/main/start.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/Metehanse/WindowsRDP/main/wallpaper.jpg -OutFile wallpaper.png
        Invoke-WebRequest https://raw.githubusercontent.com/Metehanse/WindowsRDP/main/settings.bat -OutFile settings.bat
        Invoke-WebRequest https://raw.githubusercontent.com/Metehanse/WindowsRDP/main/loop.bat -OutFile loop.bat
    - name: Preparing launcher
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/Metehanse/WindowsRDP/main/launcher/Node.js.lnk -OutFile Node.js.lnk
        Invoke-WebRequest https://raw.githubusercontent.com/Metehanse/WindowsRDP/main/launcher/Visual%20Studio%202019.lnk -OutFile "Visual Studio 2019.lnk"
    - name: Extracting Ngrok file
      run: Expand-Archive ngrok.zip
    - name: Connecting to Ngrok account.
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Enabling RDP access
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        copy Node.js.lnk C:\Users\Public\Desktop\Node.js.lnk
        copy "Visual Studio 2019.lnk" "C:\Users\Public\Desktop\Visual Studio 2019.lnk"
        copy settings.bat D:\a\settings.bat
        copy wallpaper.png C:\Windows\wallpaper.png
    - name: Customize settings
      run: 
        cmd /c REG ADD "HKCU\Control Panel\Desktop" /v WallPaper /f /t REG_SZ /d C:\Windows\wallpaper.png
        cmd /c REG ADD HKLM\SYSTEM\CurrentControlSet\Control\ComputerName\ComputerName /v ComputerName /t REG_SZ /d WindowsRDP /f
        cmd /c REG ADD HKLM\SYSTEM\CurrentControlSet\Control\ComputerName\ActiveComputerName\ /v ComputerName /t REG_SZ /d WindowsRDP /f
        cmd /c REG ADD HKLM\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\ /v Hostname /t REG_SZ /d WindowsRDP /f
        cmd /c REG ADD HKLM\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\ /v "AD Host" /t REG_SZ /d WindowsRDP /f
        cmd /c REG ADD HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\OEMInformation /v Manufacturer /t REG_SZ /d "AdHost" /f
        cmd /c REG ADD HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\OEMInformation /v Model /t REG_SZ /d "AdHost Virtual Machine" /f
        cmd /c REG ADD HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\OEMInformation /v SupportURL /t REG_SZ /d "https://github.com/Metehanse/WindowsRDP/issues" /f
        cmd /c RUNDLL32.EXE user32.dll,UpdatePerUserSystemParameters
        cmd /c rundll32 user32.dll,UpdatePerUserSystemParameters
        cmd /c ie4uinit.exe -ClearIconCache
        cmd /c taskkill /f /im explorer.exe
        cmd /c start explorer.exe
    - name: Creating tunnel
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region ap 3389"'
    - name: Connect to your RDP CPU 2 Core - 7GB Ram - 256 SSD
      run: cmd /c start.bat
    - name: RDP created successfully
      run: cmd /c loop.bat
